# Generated by Django 2.2.6 on 2019-10-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='date_created',
            new_name='date',
        ),
    ]
